### ISSUE TITLE
Error message when questionnaire is completed in Moodle app

### ISSUE THREAD

**Issue by wichmann** [PoetOS/moodle-mod_questionnaire#413]
We are using a questionnaire activity at our school for administrative purposes and it works fine when completed in the browser. In the official Moodle app an error message is shown and the response is not saved in Moodle. After clicking the button to save the answers to the questionnaire in the app, the following message is shown:

`Argument 1 passed to questionaire::build_response_from_appdata() must be an instance of stdClass, array given, called in /.../mod/questionaire/questionaire.class.php on line 4010`

The issue was confirmed with Moodle 3.11 and 4.0, the Questionnaire plugin version 3.11.0 and 3.11.1 and the newest version of the Moodle app (4.0.1). As example I included the exported Moodle activity as ZIP file: [Questionaire_Example.zip](https://github.com/PoetOS/moodle-mod_questionnaire/files/9104329/Questionaire_Example.zip)

I am not sure what the problem is and if it originates in the Moodle plugin or the Moodle app, but I would appreciate any help in solving this problem!

**Comment by Owenonthecoin** [comment]
I'm also experiencing this same error in the moodle app when submitting.  I was able to submit the same questionnaire from my laptop browser (Edge).  Moodle 3.11.2+, plugin version 3.11.1
![submitError](https://user-images.githubusercontent.com/36172602/181109905-64ee24cb-5988-460f-88e1-c45deb12facf.jpg)
,

**Comment by hn-88** [comment]
A temporary solution as suggested in the comments of 
https://moodle.org/plugins/mod_questionnaire
by https://moodle.org/user/view.php?id=24483&course=1 
is to add the line
$responses = (object) $responses;
before the line 4010

**Comment by jaschrock** [comment]
I also see the bug with the moodle mobile app 4.0.1 and Moodle 4.0.3. Adding in that line does seem to work as a temporary fix.

**Comment by mchurchward** [comment]
I believe this has been fixed in both the current MOODLE_400_STABLE and the MOODLE_311_STABLE branches. See https://github.com/PoetOS/moodle-mod_questionnaire/pull/458

**Comment by jaschrock** [comment]
I just upgraded my test server to 4.1.1 and it is still having the repeated title. :-(
![Capture](https://user-images.githubusercontent.com/24418146/222774032-dec9b18c-05d8-4de5-938c-53290f65e91e.JPG)

**Comment by jaschrock** [comment]
I also did add in a new questionnaire, just in case it was something with older entries and it is the same.

**Comment by mchurchward** [comment]
You need to upgrade your questionnaire to the latest code in the MOODLE_400_STABLE branch.
This was fixed in [this commit](https://github.com/PoetOS/moodle-mod_questionnaire/commit/d202a7b7f34642a8cc8bc23a7acdc355f3d7b8b2).

**Comment by jaschrock** [comment]
I pulled the 4.1.1 code from the latest release (not stable) last week. So, are you saying it hasn't made it yet to 4.1.1 other than MOODLE_401_STABLE. I guess I figured it would be in the next dot release already.

**Comment by mchurchward** [comment]
Questionnaire doesn't have a 4.1.1 release. The latest version of questionnaire that supports Moodle 4.1.1 is in the branch I mentioned. Also, questionnaire is not distributed with Moodle core. It is a third-party plugin managed in this repo.
You can also get the latest from the [Moodle plugin database](https://moodle.org/plugins/mod_questionnaire/4.0.0-build-2023030700/28695) now.

**Comment by jaschrock** [comment]
I realize it isn't a part of core and I was talking about Moodle release. The currently installed plugin version is 3.11.1 (Build - 2022062300)/2021062301. The rest of my plugins, with updates or doing an "check for updates" show on the list and I can upgrade them right from that interface. I thought that was the case before with this plugin, but I guess not. I can manually do it. It would be nice, though, to have that functionality available. Thanks.

**Comment by mchurchward** [comment]
A "Check for updates" should work now, as the 4.0.0 release is in the plugins database.

**Comment by jaschrock** [comment]
Hi Mike,
Yes, I saw it come through on my notifications and just applied it. All looks well. Thanks!
Alan

**Comment by mchurchward** [comment]
A "Check for updates" should work now, as the 4.0.0 release is in the plugins database.
